use_frameworks!

target 'VoucherifySwiftSdk_Example' do
  pod 'VoucherifySwiftSdk', :path => '../'

  target 'VoucherifySwiftSdk_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.0.0'
  end
end
