use_frameworks!

target 'VoucherifySwiftSdk_Example' do
  pod 'VoucherifySwiftSdk', :path => '../'

  target 'VoucherifySwiftSdk_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
